name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  keep-alive:
    runs-on: alpine-latest
    steps:
      - name: Send ping
        run: curl -X GET ${{ secrets.KA_URL }}
